### PR TITLE
[SPIKE] Allow testing of SynchronizedStorageSessionExtensions in handler.

### PR DESCRIPTION
**Pull request by boblangley**
Relates to https://github.com/Particular/NServiceBus.Testing/issues/146

### CODE REVIEW

**Comment by bording** [comment]
Hmm, if I understand the problem correctly, it's the cast to an internal class that causes the problem, right?

Instead of needing to introduce a separate public interface, what if we tried to grab the `IClientSessionHandle1` from the passed in `SynchronizedStorageSession` via reflection if the cast fails?

**Comment by boblangley** [comment]
Given the choice between the approaches, I prefer an interface over reflection/dynamic. It clearly identifies what in the `SynchronizedStorageSession` is meant to be public.

**Comment by bording** [comment]
I really don't like adding an interface to the public API surface just for testing, so maybe there's some other option.

**Comment by danielmarbach** [comment]
Another option would be to let the storage session implement `IClientSessionHandle` directly and delegate to the internal session. But that is also dangerous in case new methods get added to the interface in a minor (if they don't respect semver)

**Pull request closed without merging**
