### PR TITLE
Update to core v8

### PR DESCRIPTION
**Pull request by timbussmann**
Had to remove the additional check for active message driven subscriptions here: https://github.com/Particular/NServiceBus.Storage.MongoDB/compare/update-core-v8?expand=1#diff-b980c14e63ca949a34f6b222277ec4ddL12 as there doesn't seem to be a way to handle this without relying on internal magic strings to check. That's probably not worth it (as it could also lead to disabled subscription storage when core internals change) and therefore subscription storage is just enabled and setup by default.

### CODE REVIEW

**Review by janovesk — APPROVED** [review]

**Comment by janovesk** [comment]
Also looks good @timbussmann, but you might want to wait for the new core with MessageDrivenSubscriptions back in before merging?

**Comment by timbussmann** [comment]
yeah makes sense 👍

**Comment by timbussmann** [comment]
added DependsOn<MessageDrivenSubscriptions> back in with latest alpha.

**Review by mauroservienti — APPROVED** [review]

**Comment by mauroservienti** [comment]
@timbussmann shall we merge and push to MyGet this?

**Pull request merged**
