### PR TITLE
remove quotes in replica set initialie script

### PR DESCRIPTION
**Pull request by tmasternak**

### CODE REVIEW

**Comment by timbussmann** [comment]
@boblangley I think you added this as part of your TF with @mauroservienti. Did you have to add those quotes for some reason (e.g. are there environments where there is actually a need for `"`)? On Tomasz and my machine, the `"` definitely had to be removed.

**Comment by boblangley** [comment]
It was a mistake, remove them.

**Comment by timbussmann** [comment]
trying to figure out whether reopening the PR can retrigger the checks because they seem to be broken

**Comment by timbussmann** [comment]
merging this as admin due to the broken TC checks

**Pull request merged**
